# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Soon
email: it@koufuprinting.com
phone: +63 (46) 4137269; +63 (46) 5420227; +63 (46) 5420229; +63 (2) 5844947; +63 (2) 519 4658; +63 (2) 5525163; +63 (2) 5194575; +63 (46) 4097188;
description: A coming soon page for Kou Fu Color Printing Corporation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nostalgic-torvalds-215b10.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 
address: Lot 6-7, Block 3, Phase 2, Mountview Industrial Complex, Carmona Cavite, Philippines 4116

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
